CREATE DATABASE IF NOT EXISTS db_mutant DEFAULT CHARACTER SET utf8;
USE db_mutant;

CREATE TABLE IF NOT EXISTS person (
    id BIGINT NOT NULL AUTO_INCREMENT,
    dna VARCHAR(1000) NOT NULL,
    mutant TINYINT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX dna_UNIQUE (dna ASC));